# Build-time CTest registration for optics_tests.
#
# Run as `cmake -P` from a POST_BUILD step on the test target. It asks the
# freshly linked binary which suites it carries (`--list-suites`, which is the
# registry the runner itself iterates) and writes one `add_test` per suite into
# a file CTest includes. The hand-written list this replaces had drifted ten
# suites behind the binary, which is the failure mode a derived list cannot have.
#
# Expected on the command line, each as -D:
#   TEST_EXECUTABLE   the binary to interrogate and to register
#   TESTS_FILE        the .cmake file to write the add_test calls into
#   QT_BIN_DIR        Qt's own bin directory, prepended to PATH for both the
#                     query below and the tests themselves
#   TEST_TIMEOUT      per-suite timeout in seconds

if(NOT TEST_EXECUTABLE OR NOT TESTS_FILE)
    message(FATAL_ERROR "DiscoverSuites.cmake: TEST_EXECUTABLE and TESTS_FILE are required")
endif()

# The binary resolves Qt from PATH exactly as the tests will, so the query runs
# under the same environment the tests get rather than under a lucky one.
if(QT_BIN_DIR)
    if(WIN32)
        set(ENV{PATH} "${QT_BIN_DIR};$ENV{PATH}")
    else()
        set(ENV{PATH} "${QT_BIN_DIR}:$ENV{PATH}")
        set(ENV{LD_LIBRARY_PATH} "${QT_BIN_DIR}/../lib:$ENV{LD_LIBRARY_PATH}")
    endif()
endif()
set(ENV{QT_QPA_PLATFORM} offscreen)

execute_process(
    COMMAND "${TEST_EXECUTABLE}" --list-suites
    OUTPUT_VARIABLE suite_output
    ERROR_VARIABLE  suite_error
    RESULT_VARIABLE suite_result
    OUTPUT_STRIP_TRAILING_WHITESPACE)

# A discovery step that fails quietly would register nothing and let a green
# `ctest` mean "no tests ran". Both failure modes are fatal here instead.
if(NOT suite_result EQUAL 0)
    message(FATAL_ERROR
        "DiscoverSuites.cmake: '${TEST_EXECUTABLE} --list-suites' failed (${suite_result})\n"
        "${suite_error}")
endif()

string(REPLACE "\n" ";" suites "${suite_output}")
list(TRANSFORM suites STRIP)
list(REMOVE_ITEM suites "")

if(suites STREQUAL "")
    message(FATAL_ERROR
        "DiscoverSuites.cmake: '${TEST_EXECUTABLE} --list-suites' named no suites")
endif()

list(LENGTH suites suite_count)

set(content "# Generated by test/DiscoverSuites.cmake at build time. Do not edit.\n")
string(APPEND content "# ${suite_count} suite(s) enumerated from ${TEST_EXECUTABLE}.\n\n")

foreach(suite IN LISTS suites)
    # Bracket arguments so a suite name is passed through verbatim whatever it
    # contains; the names are identifiers today and this stops caring if they
    # ever are not.
    string(APPEND content "add_test([==[${suite}]==] [==[${TEST_EXECUTABLE}]==] [==[${suite}]==])\n")
    string(APPEND content "set_tests_properties([==[${suite}]==] PROPERTIES\n")
    string(APPEND content "    TIMEOUT ${TEST_TIMEOUT}\n")
    # Qt needs its platform plugin resolved even for a console binary on
    # Windows, and the Qt DLLs have to be findable before that can happen.
    # Prepending the kit's own bin directory to PATH does both: Qt6Core carries
    # the prefix it was built with, so the offscreen plugin resolves from there
    # without any of it being copied into the build tree. OCCT is already beside
    # the binary -- the vcpkg toolchain copies it there on every build
    # (VCPKG_APPLOCAL_DEPS) -- so a fresh clone runs ctest with nothing deployed
    # by hand.
    string(APPEND content "    ENVIRONMENT \"QT_QPA_PLATFORM=offscreen\"\n")
    string(APPEND content "    ENVIRONMENT_MODIFICATION \"PATH=path_list_prepend:${QT_BIN_DIR}\")\n\n")
endforeach()

# Only rewrite on a real change, so a rebuild that did not move any suite does
# not make CTest reconfigure.
set(previous "")
if(EXISTS "${TESTS_FILE}")
    file(READ "${TESTS_FILE}" previous)
endif()
if(NOT previous STREQUAL content)
    file(WRITE "${TESTS_FILE}" "${content}")
endif()
